remote_theme: ddc-java/ddc-day
repository_links:
  enabled: false
page_navigator:
  enabled: false
titles_from_headings:
  enabled: false

# Modify the contents below for the specific project.

title: "SmartCheff"
description: "The smart way to find recipes"
author:
  name: "Alex Garber"
  
theme: jekyll-theme-merlot